### ISSUE TITLE
The Api is not stable.

### ISSUE THREAD

**Issue by khaledhossam** [Yatko/Coronavirus-Dashboard#1]
Hello,
while i am working on the project the api is giving no responses (results).
and giving me 502 bad getway.
is this normal and its shutting down on a certain time.

**Comment by bilal1133** [comment]
Hi,
I am also facing same issue,

**Comment by Yatko** [comment]
Can you please log the time (GMT) when this happens next time and the endpoint (request).

**Comment by ica4c** [comment]
Situation resolved. Api is back online.
