### ISSUE TITLE
COVID-19 update for BD

### ISSUE THREAD

**Issue by Tasnima-Learner** [Yatko/Coronavirus-Dashboard#2]
May I use PHP instead of JS? I will store the data in database and fetch them using PHP code. and everytime the admin update the data of database it will be updated.

**Comment by Yatko** [comment]
Sure, please ask with specific details "need PHP example **today** data for **Italy** spots: **total**, **recovered**, **tested**, **...**". Asking [here](https://github.com/Yatko/Coronavirus-API/issues) may get faster answers.

**Comment by Tasnima-Learner** [comment]
Plz check the below url. Here is the corona update for my country. 
https://tasnima-learner.github.io/CoronaBD_Update/

Do you want me to do this?
please let me know what you want more on it.
