### ISSUE TITLE
Js chart

### ISSUE THREAD

**Issue by shahzadm7slabs** [Yatko/Coronavirus-Dashboard#5]

**Comment by shahzadm7slabs** [comment]
i need js chart code to eidt or plz brief how to add chart
thanks

**Comment by ica4c** [comment]
Hello @shahzadm7slabs. 
You can check parallel issue here. Reference code can be found in the example in this comment:
https://github.com/Yatko/Coronavirus-Dashboard/issues/3#issuecomment-620165089
