### ISSUE TITLE
How to change country

### ISSUE THREAD

**Issue by zakirkhaan** [Yatko/Coronavirus-Dashboard#6]
How to change country?

**Comment by ica4c** [comment]
Hello @zakirkhaan. 

In js you have two variables:
```
var countryFeedKey = 'usa';	//try china, spain, italy, etc.
var countryName = 'USA';		//try 中国, España, Italia, etc.
```
First one is an api identifier of the country you're looking for and second is just a user friendly name you want to show.
So basically if you're looking for China code these two variables should be like:
```
var countryFeedKey = 'china';	//try china, spain, italy, etc.
var countryName = '中国';		//try 中国, España, Italia, etc.
```

Italy:
```
var countryFeedKey = 'italy';	//try china, spain, italy, etc.
var countryName = 'Italia';		//try 中国, España, Italia, etc.
```

Hope it helped. If you have any additional questions feel free to ask.
