### ISSUE TITLE
chart added

### ISSUE THREAD

**Issue by khaledhossam** [Yatko/Coronavirus-Dashboard#7]
Hello,
I have added the html code as the original website but the chart is not displaying because there is missing code so i have added Egypt in the select bar and it render Egypt page from the source.

https://codepen.io/khaledhossam/project/editor/AdReoO

can i have the code of the chart ?
thanks

**Comment by ica4c** [comment]
Hello @khaledhossam. Checked your code.

Console errors:
```
Uncaught ReferenceError: Chart is not defined
    at charts.js:2
```
I'm pretty sure you run initialization code before charts js loaded. I think you should wait until DOMContentLoaded event is triggered.

Be aware that some online editors load code preview after page was loaded so you'll need an additional check for `readyState`. 

Any js code that relies on DOM manipulations or 3rd party libraries should look like this:
```
function domReady(cb) => {
  if (document.readyState === 'complete') {
    cb();
    return
  }

  document.addEventListener('readystatechange', () => {
    if (document.readyState !== 'complete') {
      return;
    }

    cb();
  });
};

domReady(() => {
*your code*
})
```

**Comment by khaledhossam** [comment]
Thank you for your consideration,

I have checked the code again and i am having problem with saving the received data to be used in the chart,
I used fetch function and it's receiving the data but i need a function to save this object in variable.

**Comment by ica4c** [comment]
Everything needed is already implemented. Check `index.js` around the line 26 for a function itself and line 80 for the usage example. You also check what js promises are and how to work with them

**Comment by khaledhossam** [comment]
It worked can you check it now and tell me your feedback

**Comment by ica4c** [comment]
Charts are good now. 

Other things I've noticed:
1) Tabs don't work. `Line`, `Bar`, `Doughnut`, `World/Country` should switch to corresponding chart. It's better for UX to keep them on separate sections. 
2) Same with today/yesterday switch. Clicking on Yesterday/Today switches throw 
`Failed to fetch data: TypeError: Cannot set property 'innerText' of null`. Check console.
3) Cleanup code. Leave one of the `master.js` or `index.js`. Don't attach both of them. This duplicates api requests.

Thank you
