### ISSUE TITLE
How to add chart need the code 

### ISSUE THREAD

**Issue by shahzadm7slabs** [Yatko/Coronavirus-Dashboard#9]

**Comment by shahzadm7slabs** [comment]
This is link of my code 
https://codepen.io/shahzad_naimi/pen/rNOzMJa

**Comment by ica4c** [comment]
Hello @shahzadm7slabs. 

Checked your code. Well done with translating. 

But there are few things I can't see:
1) Chart is not working and I can't find any chart initialization or even library import code in any of the files too. Please check `spots` endpoint in the api doc and try to implement it in your code using the sample from the original. You can use any chart library what you like i.e: https://www.chartjs.org/
2) I can see changes being hardcoded as +0. We need it to be dynamic too. Check `change` sections inside api response structure.
3) Would also be great if you managed to make `Coronavirus Top 10 Countries` selector on the bottom of the page based on the region response too.

If you'll have any questions you can't handle yourself. Feel free to ask.
Thank you.
